repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ["--strict"]
  - repo: local
    hooks:
      - id: mkdocs-build
        name: mkdocs build
        entry: mkdocs build --strict --quiet
        language: system
        files: "^(docs/|src/.*\.py$)"
