name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cpu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    env:
      IHDP_DATA: ~/.cache/otxlearner/ihdp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ matrix.python-version }}-
      - uses: actions/cache@v3
        with:
          path: ~/.cache/otxlearner
          key: ${{ runner.os }}-ihdp
      - name: Install uv
        run: python -m pip install uv
      - name: Install dependencies
        run: |
          uv pip install --system .[dev,docs,bench]
          uv pip install --system torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e .
      - name: Prepare dataset
        run: |
          python - <<'PY'
          from pathlib import Path
          from otxlearner.data import load_ihdp
          load_ihdp(Path('$IHDP_DATA'))
          PY
      - name: Ruff
        run: ruff check src tests
      - name: Black
        run: black --check src tests
      - name: Mypy
        run: mypy --strict src
      - name: Pytest
        run: pytest -vv --cov=otxlearner --cov-report=term --cov-fail-under=80
      - name: Examples smoke test
        run: python scripts/ihdp_basic.py --epochs 1 --device cpu

  cuda:
    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:2.1.2-cuda11.8-cudnn8-runtime
    env:
      IHDP_DATA: /github/home/.cache/otxlearner/ihdp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: cuda-uv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            cuda-uv-
      - uses: actions/cache@v3
        with:
          path: ~/.cache/otxlearner
          key: cuda-ihdp
      - name: Install uv
        run: python -m pip install uv
      - name: Install dependencies
        run: |
          uv pip install --system .[dev]
          pip install -e .
      - name: Prepare dataset
        run: |
          python - <<'PY'
          from pathlib import Path
          from otxlearner.data import load_ihdp
          load_ihdp(Path('$IHDP_DATA'))
          PY
      - name: Pytest
        run: pytest -vv --cov=otxlearner --cov-report=term --cov-fail-under=80

