name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cpu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    env:
      IHDP_DATA: ~/.cache/otxlearner/ihdp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
      - uses: actions/cache@v3
        with:
          path: ~/.cache/otxlearner
          key: ${{ runner.os }}-ihdp
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install torch --index-url https://download.pytorch.org/whl/cpu
          python -m pip install geomloss pytest
      - name: Prepare dataset
        run: |
          python - <<'PY'
          from pathlib import Path
          from src.data import load_ihdp
          load_ihdp(Path('$IHDP_DATA'))
          PY
      - name: Ruff
        run: ruff check src tests
      - name: Black
        run: black --check src tests
      - name: Mypy
        run: mypy --strict src
      - name: Pytest
        run: pytest -vv

  cuda:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    env:
      IHDP_DATA: /github/home/.cache/otxlearner/ihdp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: cuda-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            cuda-pip-${{ matrix.python-version }}-
      - uses: actions/cache@v3
        with:
          path: ~/.cache/otxlearner
          key: cuda-ihdp
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install torch --index-url https://download.pytorch.org/whl/cu118
          python -m pip install geomloss pytest
      - name: Prepare dataset
        run: |
          python - <<'PY'
          from pathlib import Path
          from src.data import load_ihdp
          load_ihdp(Path('$IHDP_DATA'))
          PY
      - name: Ruff
        run: ruff check src tests
      - name: Black
        run: black --check src tests
      - name: Mypy
        run: mypy --strict src
      - name: Pytest
        run: pytest -vv

