name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cpu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    env:
      IHDP_DATA: ~/.cache/otxlearner/ihdp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ matrix.python-version }}-
      - uses: actions/cache@v3
        with:
          path: ~/.cache/otxlearner
          key: ${{ runner.os }}-ihdp
      - name: Install uv
        run: python -m pip install uv
      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt
          uv pip install --system torch --index-url https://download.pytorch.org/whl/cpu
          uv pip install --system geomloss pytest
          pip install -e .
      - name: Prepare dataset
        run: |
          python - <<'PY'
          from pathlib import Path
          from otxlearner.data import load_ihdp
          load_ihdp(Path('$IHDP_DATA'))
          PY
      - name: Ruff
        run: ruff check src tests
      - name: Black
        run: black --check src tests
      - name: Mypy
        run: mypy --strict src
      - name: Pytest
        run: pytest -vv

  cuda:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
    strategy:
      matrix:
        python-version: ['3.10']
    env:
      IHDP_DATA: /github/home/.cache/otxlearner/ihdp
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        run: |
          apt-get update
          apt-get install -y software-properties-common
          add-apt-repository ppa:deadsnakes/ppa -y
          apt-get update
          apt-get install -y python${{ matrix.python-version }} python${{ matrix.python-version }}-distutils python${{ matrix.python-version }}-venv python3-pip
          ln -sf /usr/bin/python${{ matrix.python-version }} /usr/local/bin/python
          python -m pip install --upgrade pip
      - uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: cuda-uv-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            cuda-uv-${{ matrix.python-version }}-
      - uses: actions/cache@v3
        with:
          path: ~/.cache/otxlearner
          key: cuda-ihdp
      - name: Install uv
        run: python -m pip install uv
      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt
          uv pip install --system torch --index-url https://download.pytorch.org/whl/cu118
          uv pip install --system geomloss pytest
          pip install -e .
      - name: Prepare dataset
        run: |
          python - <<'PY'
          from pathlib import Path
          from otxlearner.data import load_ihdp
          load_ihdp(Path('$IHDP_DATA'))
          PY
      - name: Ruff
        run: ruff check src tests
      - name: Black
        run: black --check src tests
      - name: Mypy
        run: mypy --strict src
      - name: Pytest
        run: pytest -vv

